config/routes.rb
Rails.application.routes.draw do

  get '/phrases/translate', to: 'phrases#translate'
  resources :users_languages
  resources :users
  resources :repetitions
  resources :repetitions_phrases
  resources :phrases
  resources :languages
  resources :groups_trainees
  resources :groups_subgroups
  resources :groups_repetitions
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'phrases#translator'
end

app/models/repetition.rb
class Repetition < ApplicationRecord
  belongs_to :user
end

app/controllers/repetitions_controller.rb
class RepetitionsController < ApplicationController
  before_action :set_repetition, only: [:show, :edit, :update, :destroy]

  # GET /repetitions
  # GET /repetitions.json
  def index
    @repetitions = Repetition.all
  end

  # GET /repetitions/1
  # GET /repetitions/1.json
  def show
  end

  # GET /repetitions/new
  def new
    @repetition = Repetition.new
  end

  # GET /repetitions/1/edit
  def edit
  end

  # POST /repetitions
  # POST /repetitions.json
  def create
    @repetition = Repetition.new(repetition_params)

    respond_to do |format|
      if @repetition.save
        format.html { redirect_to @repetition, notice: 'Repetition was successfully created.' }
        format.json { render :show, status: :created, location: @repetition }
      else
        format.html { render :new }
        format.json { render json: @repetition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repetitions/1
  # PATCH/PUT /repetitions/1.json
  def update
    respond_to do |format|
      if @repetition.update(repetition_params)
        format.html { redirect_to @repetition, notice: 'Repetition was successfully updated.' }
        format.json { render :show, status: :ok, location: @repetition }
      else
        format.html { render :edit }
        format.json { render json: @repetition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repetitions/1
  # DELETE /repetitions/1.json
  def destroy
    @repetition.destroy
    respond_to do |format|
      format.html { redirect_to repetitions_url, notice: 'Repetition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repetition
      @repetition = Repetition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repetition_params
      params.require(:repetition).permit(:user_id, :positive, :negative)
    end
end

app/helpers/repetitions_helper.rb
module RepetitionsHelper
end

app/views/repetitions/_form.html.erb
<%= form_with(model: repetition, local: true) do |form| %>
  <% if repetition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repetition.errors.count, "error") %> prohibited this repetition from being saved:</h2>

      <ul>
      <% repetition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :positive %>
    <%= form.number_field :positive %>
  </div>

  <div class="field">
    <%= form.label :negative %>
    <%= form.number_field :negative %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repetitions/edit.html.erb
<h1>Editing Repetition</h1>

<%= render 'form', repetition: @repetition %>

<%= link_to 'Show', @repetition %> |
<%= link_to 'Back', repetitions_path %>

app/views/repetitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repetitions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Positive</th>
      <th>Negative</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repetitions.each do |repetition| %>
      <tr>
        <td><%= repetition.user %></td>
        <td><%= repetition.positive %></td>
        <td><%= repetition.negative %></td>
        <td><%= link_to 'Show', repetition %></td>
        <td><%= link_to 'Edit', edit_repetition_path(repetition) %></td>
        <td><%= link_to 'Destroy', repetition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repetition', new_repetition_path %>

app/views/repetitions/new.html.erb
<h1>New Repetition</h1>

<%= render 'form', repetition: @repetition %>

<%= link_to 'Back', repetitions_path %>

app/views/repetitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @repetition.user %>
</p>

<p>
  <strong>Positive:</strong>
  <%= @repetition.positive %>
</p>

<p>
  <strong>Negative:</strong>
  <%= @repetition.negative %>
</p>

<%= link_to 'Edit', edit_repetition_path(@repetition) %> |
<%= link_to 'Back', repetitions_path %>