config/routes.rb
Rails.application.routes.draw do

  get '/phrases/translate', to: 'phrases#translate'
  resources :users_languages
  resources :users
  resources :repetitions
  resources :repetitions_phrases
  resources :phrases
  resources :languages
  resources :groups_trainees
  resources :groups_subgroups
  resources :groups_repetitions
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'phrases#translator'
end

app/models/users_language.rb
class UsersLanguage < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/controllers/users_languages_controller.rb
class UsersLanguagesController < ApplicationController
  before_action :set_users_language, only: [:show, :edit, :update, :destroy]

  # GET /users_languages
  # GET /users_languages.json
  def index
    @users_languages = UsersLanguage.all
  end

  # GET /users_languages/1
  # GET /users_languages/1.json
  def show
  end

  # GET /users_languages/new
  def new
    @users_language = UsersLanguage.new
  end

  # GET /users_languages/1/edit
  def edit
  end

  # POST /users_languages
  # POST /users_languages.json
  def create
    @users_language = UsersLanguage.new(users_language_params)

    respond_to do |format|
      if @users_language.save
        format.html { redirect_to @users_language, notice: 'Users language was successfully created.' }
        format.json { render :show, status: :created, location: @users_language }
      else
        format.html { render :new }
        format.json { render json: @users_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_languages/1
  # PATCH/PUT /users_languages/1.json
  def update
    respond_to do |format|
      if @users_language.update(users_language_params)
        format.html { redirect_to @users_language, notice: 'Users language was successfully updated.' }
        format.json { render :show, status: :ok, location: @users_language }
      else
        format.html { render :edit }
        format.json { render json: @users_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_languages/1
  # DELETE /users_languages/1.json
  def destroy
    @users_language.destroy
    respond_to do |format|
      format.html { redirect_to users_languages_url, notice: 'Users language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_language
      @users_language = UsersLanguage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_language_params
      params.require(:users_language).permit(:user_id, :language_id, :primary_language)
    end
end

app/helpers/users_languages_helper.rb
module UsersLanguagesHelper
end

app/views/users_languages/_form.html.erb
<%= form_with(model: users_language, local: true) do |form| %>
  <% if users_language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_language.errors.count, "error") %> prohibited this users_language from being saved:</h2>

      <ul>
      <% users_language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :language_id %>
    <%= form.text_field :language_id %>
  </div>

  <div class="field">
    <%= form.label :primary_language %>
    <%= form.check_box :primary_language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users_languages/edit.html.erb
<h1>Editing Users Language</h1>

<%= render 'form', users_language: @users_language %>

<%= link_to 'Show', @users_language %> |
<%= link_to 'Back', users_languages_path %>

app/views/users_languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users Languages</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Language</th>
      <th>Primary language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_languages.each do |users_language| %>
      <tr>
        <td><%= users_language.user %></td>
        <td><%= users_language.language %></td>
        <td><%= users_language.primary_language %></td>
        <td><%= link_to 'Show', users_language %></td>
        <td><%= link_to 'Edit', edit_users_language_path(users_language) %></td>
        <td><%= link_to 'Destroy', users_language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users Language', new_users_language_path %>

app/views/users_languages/new.html.erb
<h1>New Users Language</h1>

<%= render 'form', users_language: @users_language %>

<%= link_to 'Back', users_languages_path %>

app/views/users_languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @users_language.user %>
</p>

<p>
  <strong>Language:</strong>
  <%= @users_language.language %>
</p>

<p>
  <strong>Primary language:</strong>
  <%= @users_language.primary_language %>
</p>

<%= link_to 'Edit', edit_users_language_path(@users_language) %> |
<%= link_to 'Back', users_languages_path %>