config/routes.rb
Rails.application.routes.draw do

  get '/phrases/translate', to: 'phrases#translate'
  resources :users_languages
  resources :users
  resources :repetitions
  resources :repetitions_phrases
  resources :phrases
  resources :languages
  resources :groups_trainees
  resources :groups_subgroups
  resources :groups_repetitions
  resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'phrases#translator'
end

app/models/groups_subgroup.rb
class GroupsSubgroup < ApplicationRecord
  belongs_to :group
  belongs_to :subgroup
end

app/controllers/groups_subgroups_controller.rb
class GroupsSubgroupsController < ApplicationController
  before_action :set_groups_subgroup, only: [:show, :edit, :update, :destroy]

  # GET /groups_subgroups
  # GET /groups_subgroups.json
  def index
    @groups_subgroups = GroupsSubgroup.all
  end

  # GET /groups_subgroups/1
  # GET /groups_subgroups/1.json
  def show
  end

  # GET /groups_subgroups/new
  def new
    @groups_subgroup = GroupsSubgroup.new
  end

  # GET /groups_subgroups/1/edit
  def edit
  end

  # POST /groups_subgroups
  # POST /groups_subgroups.json
  def create
    @groups_subgroup = GroupsSubgroup.new(groups_subgroup_params)

    respond_to do |format|
      if @groups_subgroup.save
        format.html { redirect_to @groups_subgroup, notice: 'Groups subgroup was successfully created.' }
        format.json { render :show, status: :created, location: @groups_subgroup }
      else
        format.html { render :new }
        format.json { render json: @groups_subgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups_subgroups/1
  # PATCH/PUT /groups_subgroups/1.json
  def update
    respond_to do |format|
      if @groups_subgroup.update(groups_subgroup_params)
        format.html { redirect_to @groups_subgroup, notice: 'Groups subgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @groups_subgroup }
      else
        format.html { render :edit }
        format.json { render json: @groups_subgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups_subgroups/1
  # DELETE /groups_subgroups/1.json
  def destroy
    @groups_subgroup.destroy
    respond_to do |format|
      format.html { redirect_to groups_subgroups_url, notice: 'Groups subgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groups_subgroup
      @groups_subgroup = GroupsSubgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groups_subgroup_params
      params.require(:groups_subgroup).permit(:group_id, :subgroup_id)
    end
end

app/helpers/groups_subgroups_helper.rb
module GroupsSubgroupsHelper
end

app/views/groups_subgroups/_form.html.erb
<%= form_with(model: groups_subgroup, local: true) do |form| %>
  <% if groups_subgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(groups_subgroup.errors.count, "error") %> prohibited this groups_subgroup from being saved:</h2>

      <ul>
      <% groups_subgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :subgroup_id %>
    <%= form.text_field :subgroup_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups_subgroups/edit.html.erb
<h1>Editing Groups Subgroup</h1>

<%= render 'form', groups_subgroup: @groups_subgroup %>

<%= link_to 'Show', @groups_subgroup %> |
<%= link_to 'Back', groups_subgroups_path %>

app/views/groups_subgroups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups Subgroups</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Subgroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups_subgroups.each do |groups_subgroup| %>
      <tr>
        <td><%= groups_subgroup.group %></td>
        <td><%= groups_subgroup.subgroup %></td>
        <td><%= link_to 'Show', groups_subgroup %></td>
        <td><%= link_to 'Edit', edit_groups_subgroup_path(groups_subgroup) %></td>
        <td><%= link_to 'Destroy', groups_subgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Groups Subgroup', new_groups_subgroup_path %>

app/views/groups_subgroups/new.html.erb
<h1>New Groups Subgroup</h1>

<%= render 'form', groups_subgroup: @groups_subgroup %>

<%= link_to 'Back', groups_subgroups_path %>

app/views/groups_subgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @groups_subgroup.group %>
</p>

<p>
  <strong>Subgroup:</strong>
  <%= @groups_subgroup.subgroup %>
</p>

<%= link_to 'Edit', edit_groups_subgroup_path(@groups_subgroup) %> |
<%= link_to 'Back', groups_subgroups_path %>